import React from "react";
import Line from "../Componant/cunstoms/line";
import AlertContainer from "../Componant/alertContainer";

function Home(props) {
  const datasection1 = [
    {
      id: 1,
      text: "is continually maintaining a highly qualified inspection and consultancy team, employing the latest technical expertise and paraphernalia, stressing utmost importance in safety, environment, quality, and timely completion task, and complying with all local & international regulations.",
    },
    {
      id: 1,
      text: " is continually maintaining a highly qualified inspection and consultancy team, employing the latest technical expertise and paraphernalia, stressing utmost importance in safety, environment, quality, and timely completion task, and complying with all local & international regulations.",
    },
    {
      id: 1,
      text: "is providing inspection services according to proven methods for inspection based on guidelines and Standard Operating Procedure. The Inspection and consultancy team is well organized by our Technical Manager & Training Manager and doing the task as per his authorization. is providing inspection services according to proven methods for inspection based on guidelines and Standard Operating Procedure. The Inspection and consultancy team is well organized by our Technical Manager & Training Manager and doing the task as per his authorization.",
    },
  ];

  const TypeOfWork = [
    {
      id: 1,
      img: require("../media/images/home/section3.1.png"),
      title: "Office facilities",
      hover: true,
      text1:
        "located in the heart of the city & the operations will be handled at Mussafah offices to serve the clients at anytime during the business hours. The communication between the departments and personals are established through phone, e-mails, & verbal conversations.",
      text2:
        "All the Certificates and reports are generated by the engineers to avoid delays & errors to ensure the trust of the customer",
    },
    {
      id: 1,
      img: require("../media/images/home/section3.1.png"),
      title: "Work Experience",
      text1:
        "We ABoS work with various prestigious projects with well reputed companies in UAE such as ADNATCO, NMDC, SMG, IMCC group (GPC, IMAC, GSME, CIC, ADCE), GS Engineering, Hyundai, Galfar Engineering, AL Sahraa. We can listed various projects which we handled by us on request",
    },
    {
      id: 1,
      img: require("../media/images/home/section3.1.png"),
      title: "Office facilities",
      text1:
        "ABoS is committed with High level of standardization with Quality & HSE. Our Company is certified by LEEA & ENAS for our inspection activities as per iso17020:2012 & our EHSMS system is recently certified by RINA Services for ISO14001:2004: ISO 18001:2007.",
    },
    {
      id: 1,
      img: require("../media/images/home/section3.1.png"),
      title: "Office facilities",
      text1:
        "We are the well-known and reputed company in UAE for the inspection and training activities over two decades. We have the approval with ADCO, ADMA, ZADCO, TAKREER, Al HOSN GAS; GASCO; BURAGE, FERTIL, Etc.",
    },
  ];

  return (
    <>
      <section className="section1">
        <div className="h-max pb-1 bg-thirdColor justify-center rounded-[87px] flex flex-col items-center  relative">
          <div className="w-11/12">
            <img
              className="lg:h-[836px] m:h-[500px] w-full"
              src={require("../media/images/home/Home1.png")}
              alt="Home1"
            />
            <div className="absolute top-10 lg:right-44 md:right-44  sm:right-44  xs:right-20 right-4 ">
              <div className="lg:text-[40px] md:text-3xl sm:text-2xl xs:text-2xl text-xl text-darkBlue font-bold">
                Industry experts in,
              </div>
              <div className="lg:text-[40px] md:text-3xl sm:text-2xl xs:text-2xl text-xl text-darkBlue font-bold">
                Testing,Certification,{" "}
              </div>
              <div className="lg:text-[40px] md:text-3xl sm:text-2xl xs:text-2xl text-xl text-darkBlue font-bold">
                Lifting Equipment &
              </div>
              <div className="lg:text-[40px] md:text-3xl sm:text-2xl xs:text-2xl text-xl text-darkBlue font-bold">
                Training Services
              </div>
            </div>

            <div className=" flex justify-center">
            <AlertContainer  holder="Arabian Bureau of Services"
             className="bg-overColor lg:w-10/12 h-max block py-5 " img={require("../media/images/book.png")} title1={"Company"} title2={"Profile"} doc={"Arabian Bureau of Services established on 1993 as a 3rd party inspection company for the thorough examination of Lifting Appliances, Lifting Gears, Earthmoving Machineries, Industrial Trucks & QHSE training and consultancy. During this period ABoS had grown and expanded in the U.A.E market and established a high strength relationship among its customers whose trust by its judgment. Our judgment against any equipment, machine or accessory gear gives priority of preventing equipment, machine, accessory gear, operators, labors, environment and the property from any accident, deterioration, damage, harm, fatal injuries or death. For more than two decade of operations, ABoS has gained much experience in the UAE and has preserved its commitment to provide quality inspection service to all our clients. Qualified and experienced staffs were retained to ensure a continuity of quality inspection & training services."}/>
            </div>
          </div>
        </div>
      </section>

      <section className="section2">
        <div className=" flex lg:flex-row flex-col justify-center my-3">
          <div className=" lg:w-[77%] rounded-[40px] p-2 bg-overColor relative h-max  py-4">
            <div className="lg:absolute flex flex-col justify-around -left-20 top-[13%] rounded-[20px] bg-secoundColor40 items-center 
            lg:w-[167px] h-[125px] lg:h-[167px]">
              <img
                className="lg:w-12 w-8 text-darkBlue"
                src={require("../media/images/bag.png")}
              />
              <div className=" flex flex-col">
                <span className="lg:text-[24px] text-lg font-bold text-center text-darkBlue">
                  Main
                </span>
                <span className="lg:text-[24px] text-lg font-bold text-center text-darkBlue">
                  Business
                </span>
                <span className="lg:text-[24px] text-lg font-bold text-center text-darkBlue">
                  Interest
                </span>
              </div>
            </div>

            <div className="lg:ps-40  pt-2">
              <div className="flex text-[17px]">
                <div className=" font-bold mx-1">ABoS’s</div>
                <div> is main core businesses are in the following items</div>
              </div>
              <ul className=" list-decimal font-[500] list-inside ps-2">
                <li>
                  Inspection, testing and examination of lifting appliances and
                  lifting gears.
                </li>
                <li>
                  Inspection, testing and examination of Earth moving machinery,
                  Industrial
                </li>
                <li>
                  Examination the competency of the above mentioned equipment
                  and machines operators and conducting safe use of the
                  equipment training courses for them.
                </li>
                <li>Conducting safety & Vocational training courses.</li>
              </ul>
              <div className="flex font-[500]">
                <span className=" font-bold mx-1">ABS</span>
                is doing consultation on Quality Management Systems,
                Environmental Management System and Safety Management System
                training & Consultancy
              </div>
            </div>
          </div>
        </div>
      </section>

      <section>
        <div className="  h-max bg-thirdColor rounded-t-[87px] p-4 flex justify-center">
          <div className="w-full md:w-[85%] flex  flex-col gap-5">
            <div className=" flex flex-col lg:flex-row  items-center gap-5">
              <div className=" flex flex-col w-full lg:w-2/12 ">
                <img
                  className="lg:w-[421px] w-full lg:h-[201px] "
                  alt="home"
                  src={require("../media/images/home/section3.1.png")}
                />
                <div className=" text-BlueDrak font-bold text-2xl text-center">
                  Organization
                </div>
              </div>

              <div className=" lg:w-8/12 ">
                {datasection1.map((item, index) => (
                  <div className=" mb-5">
                    <div className="text-[15px] ">
                      <span className=" font-bold me-1">ABoS</span>
                      {item.text}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <Line/>

            <div className=" grid lg:grid-cols-4 md:gap-4 xl:gap-20 2xl:gap-20 lg:gap-10">
              {TypeOfWork.map((item, index) => (
                <div className=" flex flex-col items-center">
                  <img
                    className="w-[421px] h-[201px] "
                    alt="home"
                    src={item.img}
                  />
                  <div className=" text-BlueDrak font-bold text-center text-[24px]">
                    {item.title}
                  </div>
                  <div>
                    <span
                      className={` text-[15px] font-bold ${
                        item.hover ? "visible" : "hidden"
                      }`}
                    >
                      ABS’s Abu Dhabi office
                    </span>
                    <div>{item.text1}</div>

                    <div className="mt-5"> {item.text2 && item.text2}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export default Home;
